Vidionic/Controllers/RentalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Vidionic.Controllers
{
    public class RentalsController : Controller
    {
        // GET: Rentals
        public ActionResult New()
        {
            return View();
        }
    }
}

Vidionic/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="~/Content/Site.css">
    <link rel="stylesheet" href="~/Content/styles.css">
</head>
<body>
    @Html.Partial("_NavBar")
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Vidionic</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/lib")
    @RenderSection("scripts", required: false)
</body>
</html>

Vidionic/Views/Shared/_NavBar.cshtml
 <div class="navbar navbar-inverse ">
    <div class="container">
        <div class="navbar-header">
           
            @Html.ActionLink("Vidionic", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
	        <ul class="nav navbar-nav">
		        <li>@Html.ActionLink("New Rentals", "new", "Rentals")</li>
		        <li>@Html.ActionLink("Customers", "Index", "Customers")</li>
		        <li>@Html.ActionLink("Movies", "Index", "Movies")</li>
	        </ul>
            @Html.Partial("_LoginPartial")
         </div>
     </div>
 </div>

@*<nav class="navbar navbar-expand-lg navbar-light bg-light">
	
	@Html.ActionLink("Vidionic", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })

	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav mr-auto">
			
			<li>@Html.ActionLink("Customers", "Index", "Customers")</li>
			
			<li>@Html.ActionLink("Movies", "Index", "Movies")</li>

		</ul>
		@Html.Partial("_LoginPartial")
	</div>
</nav>*@